# Generated by Django 4.2.5 on 2023-09-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_abouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouts',
            name='img',
            field=models.ImageField(default=250, upload_to='', verbose_name='picture'),
            preserve_default=False,
        ),
    ]
